# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kisiler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adsoyad', models.CharField(max_length=30, verbose_name='Adı ve Soyadı')),
                ('sinifi', models.CharField(max_length=30, verbose_name='Sınıfı')),
                ('nosu', models.CharField(max_length=30, verbose_name='Nosu')),
                ('telefonu', models.CharField(max_length=30, verbose_name='Telefonu')),
                ('aciklama', models.TextField(verbose_name='Açıklama')),
            ],
        ),
    ]
