# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 02:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_kisiler_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kisiler',
            options={'verbose_name_plural': 'Kişiler'},
        ),
        migrations.AlterModelOptions(
            name='kitaplar',
            options={'verbose_name_plural': 'Kitaplar'},
        ),
        migrations.AddField(
            model_name='kitaplar',
            name='slug',
            field=models.SlugField(default=1, editable=False, max_length=130, unique=True),
            preserve_default=False,
        ),
    ]
