# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_hareketler'),
    ]

    operations = [
        migrations.AddField(
            model_name='kisiler',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
