# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_kisiler_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kisiler',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='e-Mail'),
        ),
    ]
