# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 19:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_auto_20170904_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kisiler',
            name='adsoyad',
            field=models.CharField(max_length=60, verbose_name='Adı ve Soyadı'),
        ),
        migrations.AlterField(
            model_name='kisiler',
            name='nosu',
            field=models.CharField(max_length=60, verbose_name='Nosu'),
        ),
        migrations.AlterField(
            model_name='kisiler',
            name='sinifi',
            field=models.CharField(max_length=60, verbose_name='Sınıfı'),
        ),
        migrations.AlterField(
            model_name='kisiler',
            name='slug',
            field=models.SlugField(editable=False, max_length=70, unique=True),
        ),
        migrations.AlterField(
            model_name='kisiler',
            name='telefonu',
            field=models.CharField(max_length=60, verbose_name='Telefonu'),
        ),
        migrations.AlterField(
            model_name='kitaplar',
            name='kitapadi',
            field=models.CharField(max_length=60, verbose_name='Kitap Adı'),
        ),
        migrations.AlterField(
            model_name='kitaplar',
            name='slug',
            field=models.SlugField(editable=False, max_length=70, unique=True),
        ),
        migrations.AlterField(
            model_name='kitaplar',
            name='turu',
            field=models.CharField(max_length=60, verbose_name='Türü'),
        ),
        migrations.AlterField(
            model_name='kitaplar',
            name='yayinevi',
            field=models.CharField(max_length=60, verbose_name='Yayinevi'),
        ),
        migrations.AlterField(
            model_name='kitaplar',
            name='yazari',
            field=models.CharField(max_length=60, verbose_name='Yazarı'),
        ),
    ]
